version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}app
    container_name: backend
    build:
      context: .
      dockerfile: src/App/Dockerfile
    depends_on:
      - database

  database:
    image: postgres:14.1
    container_name: database
    environment:
      - POSTGRES_DB=trainersphere
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  database-management:
    image: dpage/pgadmin4:latest
    container_name: database-management
    depends_on:
      - database
    volumes:
      - ./.files/dev_servers.json:/pgadmin4/servers.json
      - ./.containers/database_management:/var/lib/pgadmin
    ports:
      - 5101:5101
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
